### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Infinoid** [unsafesystems/container-acme-reverse-proxy#8]
This is a very nice little tool.  I would like to use it.  Is it open source?  If so, could you please add a license file?

(Without one, I have to assume the answer "no".  https://choosealicense.com/no-permission/)

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Thanks!

**Comment by FerdinandvHagen** [comment]
Added it - feel free to use it.
